Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/For:
  Enabled: false
